// GRADE 4 STUDENTS 2024
export const Grade2 = [
  {
    CurentGrade: "Grade 2",
    StudentFullName: "OPONDO ALLAN OKOTH",
     Status:"Transferred",
     ReasonForTransfer: "koqkq",
    AdmissionNo: "",
    AssessmentNumber: "",
    EntryNo: "",
    Gender: "Male",
    classfilteringbyGender: "",
    classfilteringCode: "",
    Disability: "",
    DateOfAdm: "🕸️",
    AdmissionClass: "🕸️",
    DateOfBirth: "",
    UPI: "🕸️",
    PhoneNumber: "🕸️",
    StudentSchoolEmail: "🕸️",
    ClassTeacher: "🕸️",
    FathersName: "07xxxxxx",
    FathersPhoneNumber: "07xxxxxx",
    MothersName: "🕸️",
    MothersPhoneNumber: "🕸️",
    DateOfTransfer: "4/5/2025",
    Siblings: "No1:Tom allan \n No2: Joy amalia",
    FileUrl1: "../img/Students.jpg",
    FileUrl2: "",
    FileUrl3: "🕸️",
    FileUrl4: "",
  },
  {
    CurentGrade: "Grade 2",
    StudentFullName: "",
     Status:"Transferred",
    AdmissionNo: "",
    AssessmentNumber: "",
    EntryNo: "",
    Gender: "Male",
    classfilteringbyGender: "",
    classfilteringCode: "",
    Disability: "",
    DateOfAdm: "🕸️",
    AdmissionClass: "🕸️",
    DateOfBirth: "",
    UPI: "🕸️",
    PhoneNumber: "🕸️",
    StudentSchoolEmail: "🕸️",
    ClassTeacher: "🕸️",
    FathersName: "🕸️",
    FathersPhoneNumber: "🕸️",
    MothersName: "🕸️",
    MothersPhoneNumber: "🕸️",
    Siblings: "No1:Tom allan \n No2: Joy amalia",
    FileUrl1: "",
    FileUrl2: "",
    FileUrl3: "🕸️",
    FileUrl4: "",
  },
   
    // Add more default data objects as needed
  ];


